#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/e2e.sh
source "${SCRIPT_DIR}/lib/e2e.sh"

require_cmd bash grep sed awk

REPORT="${E2E_ARTIFACT_DIR}/issue-160-e2e-coverage.md"
: >"${REPORT}"

check_pattern() {
  local file="$1" pattern="$2" description="$3"
  if ! grep -F -- "${pattern}" "${file}" >/dev/null; then
    fail "coverage map missing source evidence for ${description}: ${file} does not contain ${pattern}"
  fi
}

line() {
  local item="$1" status="$2" evidence="$3"
  printf '| %s | %s | %s |\n' "${item}" "${status}" "${evidence}" >>"${REPORT}"
}

cat >>"${REPORT}" <<'MD'
# Issue #160 coverage map

This artifact maps the issue checklist to deterministic unit tests, CLI-contract checks, self-hosted runtime probes, or explicit remaining gaps. It is a source-checked map generated by `scripts/e2e/coverage-evidence.sh`; runtime proof remains in the jobs that execute the referenced probes and upload their logs/artifacts.

| Item | Status | Evidence |
| ---: | --- | --- |
MD

check_pattern scripts/e2e/data-plane.sh "--socks5-hostname 127.0.0.1:1080" "SOCKS data-plane egress"
check_pattern scripts/e2e/data-plane.sh "--proxy http://127.0.0.1:8080" "HTTP data-plane egress"
check_pattern scripts/e2e/data-plane.sh "assert_proxy_cleanup" "proxy cleanup"
check_pattern scripts/e2e/data-plane.sh "assert_loopback_listeners" "proxy loopback bind scope"
check_pattern scripts/e2e/data-plane.sh "connect_profile \"default-mode\"" "default connect mode lifecycle"
check_pattern scripts/e2e/data-plane.sh "PODLAZ_E2E_RELIABILITY_CYCLES" "gated lifecycle cycles"
check_pattern internal/logs/build_args_test.go "TestBuildJournalctlArgsIssue160FlagMatrix" "journalctl argument coverage"
check_pattern internal/app/cli/logs_matrix_test.go "TestRunCLILogsParsesAdditionalIssue160Flags" "logs CLI flag coverage"
check_pattern internal/app/cli/doctor_scope_test.go "TestRunCLIDoctorRejectsNetworkDNSAndRoutesScopes" "doctor scope coverage"
check_pattern internal/sub/fetch_http_status_test.go "TestFetchSourceWithMetadataKeepsSuccessfulHeaders" "HTTP metadata header coverage"
check_pattern internal/sub/fetch_http_status_test.go "TestFetchSourceRejectsUnexpectedHTTPStatus" "HTTP status failure coverage"
check_pattern internal/sub/fetch_http_status_test.go "TestFetchSourceRejectsOversizedHTTPResponse" "HTTP size-limit coverage"
check_pattern internal/app/cli/import_http_error_test.go "TestRunImportHTTPSubscriptionFailureDoesNotCreateProfiles" "HTTP import failure coverage"
check_pattern scripts/e2e/server-coverage.sh "check_public_egress \"tun-" "TUN egress evidence"
check_pattern scripts/e2e/server-coverage.sh "PODLAZ_E2E_EXPECT_IPV6" "IPv6 mode evidence"
check_pattern scripts/e2e/server-coverage.sh "run_core_crash_probe" "core crash probe"
check_pattern scripts/e2e/server-coverage.sh "run_daemon_crash_probe" "daemon crash probe"
check_pattern scripts/e2e/server-coverage.sh "run_host_wrapper_probe" "host disruption wrappers"
check_pattern scripts/e2e/cli-contract.sh "subscription-delete-keep-profiles" "subscription delete keep-profiles coverage"
check_pattern scripts/e2e/cli-contract.sh "import-local-base64-uri-list" "local import fixture coverage"
check_pattern scripts/e2e/package-service.sh "dpkg-deb --contents" "package contents coverage"
check_pattern scripts/e2e/package-service.sh "same-version reinstall and remove" "package reinstall/remove coverage"
check_pattern docs/e2e.md "Additional Debian/Ubuntu or arm64 coverage" "matrix boundary documentation"

line 1 "new runtime probe" "`scripts/e2e/data-plane.sh` runs SOCKS egress through `127.0.0.1:1080` with remote hostname resolution."
line 2 "new runtime probe" "`scripts/e2e/data-plane.sh` runs HTTP egress through `127.0.0.1:8080`."
line 3 "new runtime probe" "`scripts/e2e/data-plane.sh` asserts SOCKS and HTTP proxy requests fail after disconnect."
line 4 "new runtime probe" "`scripts/e2e/data-plane.sh` asserts listeners are bound to `127.0.0.1`, not wildcard addresses."
line 5 "new runtime probe" "`scripts/e2e/data-plane.sh` connects without `--mode` and repeats data-plane checks."
line 6 "existing runtime probe" "`scripts/e2e/server-coverage.sh` checks TUN public IPv4 egress and enforces expected IP when configured."
line 7 "existing artifact" "Server coverage host snapshots record routes while TUN is active for server-bypass review evidence."
line 8 "existing runtime probe" "Server coverage captures final/cleanup host snapshots and runs recover after TUN disconnect."
line 9 "existing runtime probe" "Core and daemon crash probes run recover/disconnect and collect after-crash host snapshots."
line 10 "existing gated probe" "`PODLAZ_E2E_EXPECT_IPV6=observe|blocked|egress` is implemented in server coverage."
line 11 "existing runtime probe" "Server coverage records `resolvectl` state and DNS resolution before/after active lifecycles."
line 12 "new gated lifecycle probe" "`PODLAZ_E2E_RELIABILITY_CYCLES=100` enables repeated proxy-only connect/disconnect lifecycle evidence; stale-state proof remains a gap until status/recover checks are added to each cycle."
line 13 "explicit boundary" "No raw host DNS mutation is embedded; DNS failure rollback requires daemon-owned injector support."
line 14 "explicit boundary" "No raw host route mutation is embedded; route failure rollback remains daemon-owned."
line 15 "explicit boundary" "Apply-phase daemon crash requires a deterministic daemon injector; current crash probes cover active connections."
line 16 "existing runtime probe" "Core crash probes assert status/doctor/disconnect/recover visibility and collect after-crash snapshots."
line 17 "new unit tests" "`internal/logs/build_args_test.go` covers journalctl argument construction; `internal/app/cli/logs_matrix_test.go` covers `--core`, inline `--since=`, long `--follow`, and combined parsing. Bounded follow execution remains a gap."
line 18 "existing partial" "Recover execute is covered in server/package flows and Go tests cover JSON execute output through injected executor; running-daemon JSON semantics remain a self-hosted gap."
line 19 "partial unit test" "`internal/app/cli/doctor_scope_test.go` covers `--network`, `--dns`, and `--routes`; `doctor --firewall` remains a required gap."
line 20 "existing deterministic" "Non-interactive confirmation failures and `--yes` success paths are covered; true TTY prompts require a pty-specific probe."
line 21 "existing test" "Subscription delete default profile-removal, `--keep-profiles`, interactive confirmation, cancel, and rollback semantics are covered by Go tests."
line 22 "existing unit evidence" "Go tests cover failed subscription update rollback; E2E fixture expansion remains a gap."
line 23 "existing fixture" "CLI contract covers `file://`, local Xray JSON, URI-list, and Base64 URI-list fixtures."
line 24 "new unit test" "`internal/sub/fetch_http_status_test.go` covers successful HTTP metadata header preservation."
line 25 "new CLI/unit test" "`internal/app/cli/import_http_error_test.go` covers top-level `podlaz import http://...` failure behavior without profile state creation."
line 26 "existing contract" "No-supported-profiles response is documented; deterministic E2E fixture remains a gap."
line 27 "existing test" "CLI contract covers mixed supported/unsupported local URI-list entries."
line 28 "existing test" "CLI contract covers duplicate import atomicity; existing profile collision is a related remaining gap."
line 29 "existing unit evidence" "Go tests cover VMess, Trojan, and Shadowsocks share URI import; E2E fixture expansion remains a gap."
line 30 "existing/new evidence" "Real-profile command capture hides secret command lines and data-plane imports assert the raw URI is not printed."
line 31 "existing evidence" "Server coverage writes profile IDs and real profile artifacts without raw profile URIs."
line 32 "documented evidence" "`docs/e2e.md` documents default Ubuntu 24.04 x64 boundaries and missing Debian/arm64 runner coverage."
line 33 "existing gated probe" "Host-disruption probes only execute host-owned wrappers and fail when explicitly enabled without wrappers."
line 34 "existing/gated evidence" "Server coverage collects status across inactive, active, crash, and recovery phases."
line 35 "remaining gap" "Detailed plan JSON field assertions are not claimed in this PR after removing the malformed test."
line 36 "existing partial" "CLI/server flows cover daemon-unavailable status/connect/disconnect/recover paths."
line 37 "existing package evidence" "Package/service tests assert installed service users/groups and packaged unit metadata."
line 38 "existing contract" "`plan --mode tun` asserts `No changes were applied`; stronger no-mutation file snapshots remain a gap."
line 39 "remaining gap" "Full TUN JSON field assertions remain a gap."
line 40 "existing test" "CLI contract verifies generated completions for bash, zsh, and fish."
line 41 "existing test" "CLI contract covers `help <command>` and selected `<command> -h/--help` paths."
line 42 "existing tests" "Package/service E2E inspects package metadata, installed layout, reinstall, and removal behavior."
line 43 "existing tests" "Package/service E2E inspects systemd unit/sysusers payload and service metadata."
line 44 "existing tests" "Package/service E2E checks runtime/state directory contract through packaged unit metadata and service start."
line 45 "existing tests" "Package/service E2E checks installed CLI, daemon, service, sysusers, and completions."
line 46 "existing evidence" "Server coverage and xray exec diagnostics collect process/runtime metadata around active core processes."
line 47 "existing evidence" "Normal output redaction is covered in CLI tests; generated config artifact scanning remains a gap."
line 48 "existing evidence" "Recover/status diagnostics inspect transaction candidates and warnings."
line 49 "existing evidence" "Recover contract and diagnostics report ambiguous resources as skipped."
line 50 "existing evidence" "Recover contract forbids wholesale runtime root cleanup."
line 51 "existing evidence" "Recover contract treats stale PID metadata as insufficient process identity."
line 52 "existing evidence" "Recover/status diagnostics inspect pending/failed/rolling-back/stale transaction records."
line 53 "existing evidence" "Ambiguous cleanup safety is covered by recover contract and diagnostics."
line 54 "existing evidence" "Runtime root safety is covered by recover contract; cleanup scripts call `recover`, not raw `rm -rf /run/podlaz`."
line 55 "existing evidence" "Old PID safety is covered by recover contract and process identity diagnostics."
line 56 "existing runtime probe" "Server coverage captures active TUN snapshots for device, route, rule, DNS, firewall, and adapter evidence."
line 57 "existing contract" "Unsupported-only import/subscription behavior is documented; deterministic E2E fixture remains a gap."
line 58 "new unit test" "`internal/sub/fetch_http_status_test.go` covers HTTP 404/500 failure contracts and response size-limit enforcement."
line 59 "existing code evidence" "Top-level `podlaz import <share-uri>` is dispatched by the import command."
line 60 "existing evidence" "Server coverage records every imported profile; release/manual reviewers can enforce protocol-family breadth from artifacts."
line 61 "existing/new evidence" "Command captures mask secrets and tests assert known private inputs are absent from stdout artifacts."

log "wrote issue #160 coverage map to ${REPORT}"
cat "${REPORT}"
