#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/e2e.sh
source "${SCRIPT_DIR}/lib/e2e.sh"

require_cmd bash grep sed awk

REPORT="${E2E_ARTIFACT_DIR}/issue-160-e2e-coverage.md"
: >"${REPORT}"

check_pattern() {
  local file="$1" pattern="$2" description="$3"
  if ! grep -F -- "${pattern}" "${file}" >/dev/null; then
    fail "coverage map missing source evidence for ${description}: ${file} does not contain ${pattern}"
  fi
}

line() {
  local item="$1" status="$2" evidence="$3"
  printf '| %s | %s | %s |\n' "${item}" "${status}" "${evidence}" >>"${REPORT}"
}

cat >>"${REPORT}" <<'MD'
# Issue #160 coverage map

This artifact maps the issue checklist to deterministic unit tests, CLI-contract checks, self-hosted runtime probes, or explicit remaining gaps. It is a source-checked map generated by `scripts/e2e/coverage-evidence.sh`; runtime proof remains in the jobs that execute the referenced probes and upload their logs/artifacts.

| Item | Status | Evidence |
| ---: | --- | --- |
MD

check_pattern scripts/e2e/data-plane.sh "--socks5-hostname 127.0.0.1:1080" "SOCKS data-plane egress"
check_pattern scripts/e2e/data-plane.sh "--proxy http://127.0.0.1:8080" "HTTP data-plane egress"
check_pattern scripts/e2e/data-plane.sh "assert_proxy_cleanup" "proxy cleanup"
check_pattern scripts/e2e/data-plane.sh "assert_loopback_listeners" "proxy loopback bind scope"
check_pattern scripts/e2e/data-plane.sh "connect_profile \"default-mode\"" "default connect mode lifecycle"
check_pattern scripts/e2e/data-plane.sh "PODLAZ_E2E_RELIABILITY_CYCLES" "gated lifecycle cycles"
check_pattern scripts/e2e/data-plane.sh "assert_no_stale_state" "post-disconnect status/recover stale-state coverage"
check_pattern scripts/e2e/data-plane.sh "assert_proxy_egress http \"reliability-" "HTTP egress inside reliability loop"
check_pattern internal/logs/build_args_test.go "TestBuildJournalctlArgsIssue160FlagMatrix" "journalctl argument coverage"
check_pattern internal/app/cli/logs_matrix_test.go "TestRunCLILogsParsesAdditionalIssue160Flags" "logs CLI flag coverage"
check_pattern scripts/e2e/cli-contract.sh "logs-follow-short-bounded" "bounded logs -f coverage"
check_pattern scripts/e2e/cli-contract.sh "logs-follow-long-bounded" "bounded logs --follow coverage"
check_pattern internal/app/cli/doctor_scope_test.go "TestRunCLIDoctorRejectsDeferredScopes" "doctor scope coverage"
check_pattern scripts/e2e/cli-contract.sh "doctor-scope-network" "doctor network scope coverage"
check_pattern scripts/e2e/cli-contract.sh "doctor-scope-dns" "doctor dns scope coverage"
check_pattern scripts/e2e/cli-contract.sh "doctor-scope-routes" "doctor routes scope coverage"
check_pattern scripts/e2e/cli-contract.sh "doctor-scope-firewall" "doctor firewall scope coverage"
check_pattern internal/sub/fetch_http_status_test.go "TestFetchSourceWithMetadataKeepsSuccessfulHeaders" "HTTP metadata header coverage"
check_pattern internal/sub/fetch_http_status_test.go "TestFetchSourceRejectsUnexpectedHTTPStatus" "HTTP status failure coverage"
check_pattern internal/sub/fetch_http_status_test.go "TestFetchSourceRejectsOversizedHTTPResponse" "HTTP size-limit coverage"
check_pattern internal/app/cli/import_http_error_test.go "TestRunImportHTTPSubscriptionFailureDoesNotCreateProfiles" "HTTP import failure coverage"
check_pattern scripts/e2e/server-coverage.sh "check_public_egress \"tun-" "TUN egress evidence"
check_pattern scripts/e2e/server-coverage.sh "PODLAZ_E2E_EXPECT_IPV6" "IPv6 mode evidence"
check_pattern scripts/e2e/server-coverage.sh "run_core_crash_probe" "core crash probe"
check_pattern scripts/e2e/server-coverage.sh "run_daemon_crash_probe" "daemon crash probe"
check_pattern scripts/e2e/server-coverage.sh "run_host_wrapper_probe" "host disruption wrappers"
check_pattern scripts/e2e/cli-contract.sh "subscription-delete-keep-profiles" "subscription delete keep-profiles coverage"
check_pattern scripts/e2e/cli-contract.sh "import-local-base64-uri-list" "local import fixture coverage"
check_pattern scripts/e2e/package-service.sh "dpkg-deb --contents" "package contents coverage"
check_pattern scripts/e2e/package-service.sh "same-version reinstall and remove" "package reinstall/remove coverage"
check_pattern docs/e2e.md "Additional Debian/Ubuntu or arm64 coverage" "matrix boundary documentation"

line 1 "new runtime probe" "SOCKS proxy egress through loopback listener."
line 2 "new runtime probe" "HTTP proxy egress through loopback listener."
line 3 "new runtime probe" "SOCKS and HTTP proxy requests fail after disconnect."
line 4 "new runtime probe" "Proxy listeners are loopback-only."
line 5 "new runtime probe" "Default connect mode repeats data-plane checks."
line 6 "existing runtime probe" "TUN public IPv4 egress is checked by server coverage."
line 7 "existing artifact" "Server coverage records route snapshots while TUN is active."
line 8 "existing runtime probe" "Server coverage captures final cleanup snapshots and runs recovery checks."
line 9 "existing runtime probe" "Core and daemon crash probes collect after-crash snapshots."
line 10 "existing gated probe" "IPv6 observe/blocked/egress modes are implemented in server coverage."
line 11 "existing runtime probe" "DNS state and resolution are recorded before and after active lifecycles."
line 12 "new gated runtime probe" "100-cycle mode now checks loopback listeners, SOCKS egress, HTTP egress, cleanup, status, and recovery dry-run after every disconnect."
line 13 "explicit boundary" "DNS rollback fault injection still needs daemon-owned injector support."
line 14 "explicit boundary" "Route rollback fault injection still needs daemon-owned injector support."
line 15 "explicit boundary" "Apply-phase daemon crash still needs a deterministic injector."
line 16 "existing runtime probe" "Core crash probes assert status/doctor/disconnect/recover visibility."
line 17 "new unit and CLI probes" "Logs argument construction, CLI parsing, and bounded follow execution are covered."
line 18 "existing partial" "Recover execute and JSON output are partly covered; running-daemon JSON semantics remain a self-hosted gap."
line 19 "new CLI probe" "Planned doctor scopes are covered by Go tests plus explicit CLI-contract scope probes."
line 20 "existing deterministic" "Non-interactive confirmation and yes paths are covered; true TTY prompt remains a gap."
line 21 "existing test" "Subscription delete default removal, keep, confirmation, cancel, and rollback semantics are covered."
line 22 "existing unit evidence" "Failed subscription update rollback is covered; E2E fixture expansion remains a gap."
line 23 "existing fixture" "Local import fixtures cover file, JSON, URI-list, and Base64 URI-list."
line 24 "new unit test" "HTTP metadata header preservation is covered."
line 25 "new CLI/unit test" "HTTP import failure preserves profile state."
line 26 "existing contract" "No-supported-profiles behavior is documented; deterministic E2E fixture remains a gap."
line 27 "existing test" "Mixed supported/unsupported URI-list entries are covered."
line 28 "existing test" "Duplicate import atomicity is covered; existing profile collision remains a related gap."
line 29 "existing unit evidence" "VMess, Trojan, and Shadowsocks share URI import are covered by unit tests."
line 30 "existing/new evidence" "Known private inputs are not printed in stdout artifacts."
line 31 "existing evidence" "Real-profile artifacts store profile IDs, not raw profile URIs."
line 32 "documented evidence" "Default runner matrix boundaries are documented."
line 33 "existing gated probe" "Host-disruption probes require explicit host-owned wrappers."
line 34 "existing/gated evidence" "Status is collected across inactive, active, crash, and recovery phases."
line 35 "remaining gap" "Detailed plan JSON field assertions are not claimed in this PR after removing the malformed test."
line 36 "existing partial" "Daemon-unavailable status/connect/disconnect/recover paths are covered."
line 37 "existing package evidence" "Installed service users/groups and unit metadata are asserted."
line 38 "existing contract" "TUN plan says no changes were applied; stronger no-mutation snapshots remain a gap."
line 39 "remaining gap" "Full TUN JSON field assertions remain a gap."
line 40 "existing test" "Shell completions are covered."
line 41 "existing test" "Help paths are covered."
line 42 "existing tests" "Package metadata, installed layout, reinstall, and removal are covered."
line 43 "existing tests" "Packaged service metadata is inspected."
line 44 "existing tests" "Runtime/state directory contract is checked through package/service tests."
line 45 "existing tests" "Installed CLI, daemon, service, sysusers, and completions are checked."
line 46 "existing evidence" "Process/runtime metadata is collected around active core processes."
line 47 "existing evidence" "Normal output redaction is covered; generated config artifact scanning remains a gap."
line 48 "existing evidence" "Recovery/status diagnostics inspect candidates and warnings."
line 49 "existing evidence" "Ambiguous recovery candidates are reported as skipped."
line 50 "existing evidence" "Recovery contract forbids broad runtime-root cleanup."
line 51 "existing evidence" "Stale PID metadata is insufficient process identity."
line 52 "existing evidence" "Transaction records are inspected by recover/status diagnostics."
line 53 "existing evidence" "Ambiguous cleanup safety is covered by recovery diagnostics."
line 54 "existing evidence" "Cleanup scripts call recovery flow instead of deleting runtime roots directly."
line 55 "existing evidence" "Old PID safety is covered by process identity diagnostics."
line 56 "existing runtime probe" "Server coverage captures active TUN snapshots for device, routes, rules, DNS, filters, and adapter evidence."
line 57 "existing contract" "Unsupported-only import/subscription behavior is documented."
line 58 "new unit test" "HTTP 404/500 and response size-limit contracts are covered."
line 59 "existing code evidence" "Top-level share-URI import dispatch is implemented."
line 60 "existing evidence" "Server coverage records every imported profile for manual protocol-family review."
line 61 "existing/new evidence" "Command captures mask secrets and tests assert known private inputs are absent from stdout artifacts."

log "wrote issue #160 coverage map to ${REPORT}"
cat "${REPORT}"
